//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseKeepingSchedule
    {
        public int ScheduleID { get; set; }
        public string ScheduleType { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public string Status { get; set; }
        public string Details { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
