//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnderTheSeaEntities : DbContext
    {
        private static UnderTheSeaEntities en;
        private UnderTheSeaEntities()
            : base("name=UnderTheSeaEntities")
        {
        }
        public static UnderTheSeaEntities getInstance()
        {
            if (en== null)
            {
                Console.WriteLine("DataContext Created!");
                en = new UnderTheSeaEntities();
            }
            return en;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<AttractionRequest> AttractionRequests { get; set; }
        public virtual DbSet<ConstructionRequest> ConstructionRequests { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeDischargeRequest> EmployeeDischargeRequests { get; set; }
        public virtual DbSet<FundRequest> FundRequests { get; set; }
        public virtual DbSet<HouseKeepingSchedule> HouseKeepingSchedules { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<LeaveRequest> LeaveRequests { get; set; }
        public virtual DbSet<MaintenanceSchedule> MaintenanceSchedules { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderHeader> OrderHeaders { get; set; }
        public virtual DbSet<Parade> Parades { get; set; }
        public virtual DbSet<PurchaseRequest> PurchaseRequests { get; set; }
        public virtual DbSet<Ride> Rides { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<WorkPerformance> WorkPerformances { get; set; }
    }
}
