//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parade
    {
        public int ActivityID { get; set; }
        public string ActivityType { get; set; }
        public string ActivityName { get; set; }
        public int ActivityDuration { get; set; }
        public string ActivityDescription { get; set; }
        public string Status { get; set; }
        public int PeopleCount { get; set; }
    }
}
