//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.HouseKeepingSchedules = new HashSet<HouseKeepingSchedule>();
        }
    
        public int RoomID { get; set; }
        public string RoomType { get; set; }
        public int RoomPrice { get; set; }
        public int RoomCapacity { get; set; }
        public string RoomCondition { get; set; }
        public string RoomStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseKeepingSchedule> HouseKeepingSchedules { get; set; }
    }
}
