//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public string TicketType { get; set; }
        public int TicketPrice { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
        public string TicketStatus { get; set; }
    }
}
